version: "3"
services:
  dev:
    build: .
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/bus/usb:/dev/bus/usb
      - ..:/workspace
    network_mode: host
    privileged: true
    command: tail -f /dev/null